[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:python3_host_prog = '/usr/local/bin/python3'
'''

[[plugins]]
repo = 'kentarosasaki/vim-emacs-bindings'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  " set lightline theme inside lightline config
  let g:lightline = { 'colorscheme': 'tender' }
'''
